import { CompanyCoursesInfo, PeopleCoursesInfo } from "./types";

export const CompanyCourses: CompanyCoursesInfo[] = [
    {
       title: 'NR 6 –EPI – Equipamento de Proteção Individual',
       subtitle: 'Utilização, guarda e conservação (inicial e Reciclagem)',
       availability: 2,
       description: 'Este treinamento é ideal para colaboradoes e empresas que envolva qualquer atividade que possua algum tipo de risco físico necessário a utilização do equipamento de proteção individual (EPI). Esses equipamentos são indispensáveis afim de preservar a saúde física do colaborador. ',
       horary: '4 horas',
    },
    {
        title: 'NR 10 - Segurança em Instalações e Serviços de Eletricidade',
        subtitle: '(Básico, SEP e Reciclagem)',
        availability: 2,
        description: 'Treinamento que tem por objetivo a capacitação e a qualificação do trabalhador que irá atuar com segurança em instalações elétricas e serviços com eletricidade. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        horary: '4 horas a 40 horas, depedendendo do curso',
     },
     {
        title: 'NR 11 – Operador de Empilhadeira',
        subtitle: 'Capacitação, reciclagem 100% online',
        availability: 2,
        description: 'O curso de NR 11 é fundamental para todos os profissionais que irão atuar com empilhadeira em diversos seguimentos de carga e descarga de materiais, empilhamento por processo mecanizado, que além de capacitar, instrui sobe o gerenciamento de riscos dos colaboradores. Deixando apto para o trabalho e regulamentado conforme as normativas do ministério do trabalho exigem.',
        horary: '16 horas',
     },
     {
        title: 'NR 11 – Operador de Máquinas Agrícolas e Equipamentos',
        subtitle: '(Capacitação e Reciclagem)',
        availability: 2,
        description: 'Operador de máquinas agrícolas e equipamentos, tem o objetivo de instruir e capacitar pessoas que necessitem operar máquinas agrícolas de forma segura, com eficácia e respeitando as normas do TEM, para a sua proteção, dos seus colegas de trabalho de visitantes e da empresa',
        horary: '16 horas',
     },
     {
        title: 'NR 11 – Operador de Muque',
        subtitle: '(Capacitação e Reciclagem)',
        availability: 2,
        description: 'O curso é fundamental para todos os profissionais que irão atuar com caminhão muque em diversos seguimentos de carga e descarga de materiais, empilhamento por processo mecanizado, que além de capacitar, instrui sobre o gerenciamento de riscos dos colaboradores. Deixando apto para o trabalho e regulamentado conforme as normativas do ministério do trabalho exigem.',
        horary: '8 horas',
     },
     {
        title: 'NR 11 – Operador de Ponte Rolante e Talha',
        subtitle: '(Capacitação e Reciclagem)',
        availability: 2,
        description: 'Tem como objetivo qualificar e aprimorar os conhecimentos do profissional que a opera, como funciona, manutenção, técnicas de correto manuseio da máquina e possibilitar noções sobre a legislação e suas atribuições no local de trabalho. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        horary: '16 horas',
     },
     {
        title: 'NR 11 – Operador de Hilo Tombador',
        subtitle: '(Capacitação e Reciclagem)',
        availability: 2,
        description: 'O curso de capacitação para operador de Hilo Tombador, tem o objetivo de instruir e capacitar profissionais para estarem aptos a operar com segurança, equipamento responsável por meio de tração, pela elevação de cargas e materiais de difícil locomoção, como é o caso do Hilo Tombador. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        horary: '5 horas',
     },

     {
        title: 'NR 12 – Segurança em Máquinas e Equipamentos',
        subtitle: 'Inicial e Reciclagem',
        availability: 2,
        description: 'O curso de NR 12 é destinado a operadores de máquinas e equipamentos. Tem como objetivo capacitar o profissional para identificar fatores de risco e utilizar as melhores práticas para a prevenção de acidentes no uso de seus instrumentos de trabalho. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        horary: '2 horas',
     },


     {
        title: 'NR 17 – Ergonomia',
        subtitle: 'Operador de Check-out , trabalho em teleatendimento/telemarketing',
        availability: 2,
        description: 'Esta norma regulamentadora visa estabelecer parâmetros que permitam a adaptação das condições de trabalho as características psicofisiológicas dos trabalhadores, proporcionando o máximo de conforto segurança e desempenho eficiente aos colaboradores.',
        horary: '2 ou 4 horas a depender do curso',
     },

     {
        title: 'NR 18 – Condição e Meio Ambiente na Construção Civil',
        subtitle: 'Inicial e Reciclagem',
        availability: 2,
        description: 'Esta norma regulamentadora é destinada a trabalhadores da construção civil e aborda os riscos e medidas necessárias nas condições e no meio ambiente de trabalho na indústria da construção.',
        horary: '4 ou 16 horas a depender do curso'
     },
     {
        title: 'NR 20 – Inflamáveis e Combustíveis',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        availability: 2,
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho. ',
        horary: '16 ou 32 horas a depender do curso'
     },
     {
        title: 'NR 23 – Proteção e Combate a Incêndio',
        subtitle: 'Proteção contra incêndios no ambiente de trabalho',
        availability: 2,
        description: 'Esta norma regulamentadora é destinado a profissionais para conhecer os conceitos e aprimorar seus conhecimentos sobre a área de combate dos princípios de incêndios. ',
        horary: '16 horas'
     },
     {
        title: 'Primeiros Socorros',
        subtitle: 'Bombeiros, brigadistas, etc',
        availability: 2,
        description: 'O Treinamento de Primeiros Socorros aborda todo conteúdo sobre as técnicas de primeiros socorros e o conjunto de medidas de prevenção, para ser aplicado em casos de necessidade.',
        horary: '10 horas'
     },
     {
        title: 'Direção Defensiva',
        subtitle: 'Veículos Leves e Pesados',
        availability: 2,
        description: 'O Curso de Direção Defensiva aborda todo conteúdo sobre as técnicas de direção defensiva e o conjunto de medidas de prevenção de acidentes no trânsito.',
        horary: '6 horas'
     },
     {
        title: 'Nr 33 – Segurança e Saúde em Espaços Confinados',
        subtitle: 'Trabalhador autorizado, Vigia e Supervisor – Básico e reciclagem',
        availability: 2,
        description: 'Esta norma tem como objetivo estabelecer os requisitos mínimos para identificação de espaços confinados e o reconhecimento, avaliação, monitoramento e controle dos riscos existentes, de forma a garantir permanentemente a segurança dos trabalhadores que interagem direta ou indiretamente nestes espaços.',
        horary: '8, 16 e 40 horas de conteúdo a depender do curso'
     },
     {
        title: 'Nr 35 - Trabalho em Altura',
        subtitle: 'Básico e Reciclagem ',
        availability: 2,
        description: 'Esta norma regulamentadora tem como objetivo capacitar o profissional para realizar trabalho em altura. Dentre elas envolve o planejamento, organização e execução da função, visa a segurança e a saúde dos trabalhadores envolvidos com atividades de risco de quedas. Deixando apto para o trabalho e regulamentado conforme as exigências no ministério do trabalho.',
        horary: '4 e 8 horas de conteúdo a depender do curso'
     },
    ]

export const peopleCourses: PeopleCoursesInfo[] = [
    {
        title: 'NR 5 – CIPA',
        subtitle: 'Formação de Cipeiros ( Grau de risco 1, 2, 3 e 4)',
        description: 'Este treinamento tem como finalidade educar para prática de segurança do trabalho tendo a comissão interna de prevenção de acidentes, constituída por representantes  indicados pelo empregador e membros eleitos pelos trabalhadores, em cada estabelecimento da empresa, que tem a finalidade de prevenir acidentes e doenças decorrentes do trabalho, de modo a tornar compatível permanentemente o trabalho com a preservação da vida e promoção da saúde do trabalhador.',
        price: '67,90',
        horary: '8 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'CIPA GRAU DE RISCO I',
        subtitle: 'Formação de Cipeiros ( Grau de risco 1, 2, 3 e 4)',
        description: 'Este treinamento tem como finalidade educar para prática de segurança do trabalho tendo a comissão interna de prevenção de acidentes, constituída por representantes  indicados pelo empregador e membros eleitos pelos trabalhadores, em cada estabelecimento da empresa, que tem a finalidade de prevenir acidentes e doenças decorrentes do trabalho, de modo a tornar compatível permanentemente o trabalho com a preservação da vida e promoção da saúde do trabalhador.',
        price: '67,90',
        horary: '8 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'CIPA GRAU DE RISCO II',
        subtitle: 'Formação de Cipeiros ( Grau de risco 1, 2, 3 e 4)',
        description: 'Este treinamento tem como finalidade educar para prática de segurança do trabalho tendo a comissão interna de prevenção de acidentes, constituída por representantes  indicados pelo empregador e membros eleitos pelos trabalhadores, em cada estabelecimento da empresa, que tem a finalidade de prevenir acidentes e doenças decorrentes do trabalho, de modo a tornar compatível permanentemente o trabalho com a preservação da vida e promoção da saúde do trabalhador.',
        price: '67,90',
        horary: '8 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'CIPA GRAU DE RISCO III',
        subtitle: 'Formação de Cipeiros ( Grau de risco 1, 2, 3 e 4)',
        description: 'Este treinamento tem como finalidade educar para prática de segurança do trabalho tendo a comissão interna de prevenção de acidentes, constituída por representantes  indicados pelo empregador e membros eleitos pelos trabalhadores, em cada estabelecimento da empresa, que tem a finalidade de prevenir acidentes e doenças decorrentes do trabalho, de modo a tornar compatível permanentemente o trabalho com a preservação da vida e promoção da saúde do trabalhador.',
        price: '67,90',
        horary: '8 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'Conhecendo as NRs - Básico',
        subtitle: 'Integrando um novo colaborador apresentando a aplicação de cada NR.',
        description: 'Este treinamento é voltado a gestores e a todos com interesse em conhecer as aplicações das NR’s, o objetivo é transmitir um resumo da aplicação de cada NR. Assim como documentação e responsabilidade de modo geral.',
        price: '45,90',
        horary: '8 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 06- EPI EQUIPAMENTO DE PROTEÇÃO INDIVIDUAL',
        subtitle: 'Utilização, guarda e conservação (inicial e Reciclagem)',
        description: 'Este treinamento é ideal para colaboradoes e empresas que envolva qualquer atividade que possua algum tipo de risco físico necessário a utilização do equipamento de proteção individual (EPI). Esses equipamentos são indispensáveis afim de preservar a saúde física do colaborador.',
        price: '48,90',
        horary: '4 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 06- EPI EQUIPAMENTO DE PROTEÇÃO INDIVIDUAL (RECICLAGEM)',
        subtitle: 'Utilização, guarda e conservação (inicial e Reciclagem)',
        description: 'Este treinamento é ideal para colaboradoes e empresas que envolva qualquer atividade que possua algum tipo de risco físico necessário a utilização do equipamento de proteção individual (EPI). Esses equipamentos são indispensáveis afim de preservar a saúde física do colaborador.',
        price: '48,90',
        horary: '4 horas',
        avaliable: '24 meses',
        link: '',
    },
    {
        title: 'NR 10 - Segurança em Instalações e Serviços de Eletricidade - BÁSICO',
        subtitle: '(Básico, SEP e Reciclagem)',
        description: 'Treinamento que tem por objetivo a capacitação e a qualificação do trabalhador que irá atuar com segurança em instalações elétricas e serviços com eletricidade. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '128,90',
        horary: '40 horas',
        avaliable: '24 meses',
        link: '',
    },
    {
        title: 'NR 10 - Segurança em Instalações e Serviços de Eletricidade - SISTEMA ELÉTRICO DE POTÊNCIA (SEP)',
        subtitle: '(Básico, SEP e Reciclagem)',
        description: 'Treinamento que tem por objetivo a capacitação e a qualificação do trabalhador que irá atuar com segurança em instalações elétricas e serviços com eletricidade. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '165,90',
        horary: '40 horas',
        avaliable: '24 meses',
        link: '',
    },
    {
        title: 'NR 11 – Operador de Empilhadeira - PARTE TEÓRICA',
        subtitle: 'Capacitação, reciclagem 100% online',
        description: 'O curso de NR 11 é fundamental para todos os profissionais que irão atuar com empilhadeira em diversos seguimentos de carga e descarga de materiais, empilhamento por processo mecanizado, que além de capacitar, instrui sobe o gerenciamento de riscos dos colaboradores. Deixando apto para o trabalho e regulamentado conforme as normativas do ministério do trabalho exigem.',
        price: '199,90',
        horary: '16 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 11 – Operador de Máquinas Agrícolas e Equipamentos - TEÓRICA',
        subtitle: '(Capacitação e Reciclagem)',
        description: 'Operador de máquinas agrícolas e equipamentos, tem o objetivo de instruir e capacitar pessoas que necessitem operar máquinas agrícolas de forma segura, com eficácia e respeitando as normas do TEM, para a sua proteção, dos seus colegas de trabalho de visitantes e da empresa.',
        price: '199,90',
        horary: '16 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 11 – Operador de Muque',
        subtitle: '(Capacitação e Reciclagem)',
        description: 'O curso é fundamental para todos os profissionais que irão atuar com caminhão muque em diversos seguimentos de carga e descarga de materiais, empilhamento por processo mecanizado, que além de capacitar, instrui sobre o gerenciamento de riscos dos colaboradores. Deixando apto para o trabalho e regulamentado conforme as normativas do ministério do trabalho exigem.',
        price: '199,90',
        horary: '8 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 11 – Operador de Ponte Rolante e Talha',
        subtitle: '(Capacitação e Reciclagem)',
        description: 'Tem como objetivo qualificar e aprimorar os conhecimentos do profissional que a opera, como funciona, manutenção, técnicas de correto manuseio da máquina e possibilitar noções sobre a legislação e suas atribuições no local de trabalho. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '199,90',
        horary: '16 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 11 – Operador de Hilo Tombador',
        subtitle: '(Capacitação e Reciclagem)',
        description: 'O curso de capacitação para operador de Hilo Tombador, tem o objetivo de instruir e capacitar profissionais para estarem aptos a operar com segurança, equipamento responsável por meio de tração, pela elevação de cargas e materiais de difícil locomoção, como é o caso do Hilo Tombador. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '199,90',
        horary: '5 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 12 – Segurança em Máquinas e Equipamentos - BÁSICO',
        subtitle: 'Inicial e Reciclagem',
        description: 'O curso de NR 12 é destinado a operadores de máquinas e equipamentos. Tem como objetivo capacitar o profissional para identificar fatores de risco e utilizar as melhores práticas para a prevenção de acidentes no uso de seus instrumentos de trabalho. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '199,90',
        horary: '8 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 12 – Segurança em Máquinas e Equipamentos - RECLICLAGEM',
        subtitle: 'Inicial e Reciclagem',
        description: 'O curso de NR 12 é destinado a operadores de máquinas e equipamentos. Tem como objetivo capacitar o profissional para identificar fatores de risco e utilizar as melhores práticas para a prevenção de acidentes no uso de seus instrumentos de trabalho. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '199,90',
        horary: '8 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 17 – Ergonomia - BÁSICO',
        subtitle: 'Operador de Check-out , trabalho em teleatendimento/telemarketing',
        description: 'Esta norma regulamentadora visa estabelecer parâmetros que permitam a adaptação das condições de trabalho as características psicofisiológicas dos trabalhadores, proporcionando o máximo de conforto segurança e desempenho eficiente aos colaboradores.',
        price: '67,90',
        horary: '2 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 17 – Ergonomia - OPERADORES DE CHECK-OUT',
        subtitle: 'Operador de Check-out , trabalho em teleatendimento/telemarketing',
        description: 'Esta norma regulamentadora visa estabelecer parâmetros que permitam a adaptação das condições de trabalho as características psicofisiológicas dos trabalhadores, proporcionando o máximo de conforto segurança e desempenho eficiente aos colaboradores.',
        price: '67,90',
        horary: '2 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 18 – Condição e Meio Ambiente na Construção Civil - BÁSICO 4H',
        subtitle: 'Inicial e Reciclagem',
        description: 'Esta norma regulamentadora é destinada a trabalhadores da construção civil e aborda os riscos e medidas necessárias nas condições e no meio ambiente de trabalho na indústria da construção.',
        price: '58,90',
        horary: '4 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 18 – Condição e Meio Ambiente na Construção Civil - RECLICLAGEM',
        subtitle: 'Inicial e Reciclagem',
        description: 'Esta norma regulamentadora é destinada a trabalhadores da construção civil e aborda os riscos e medidas necessárias nas condições e no meio ambiente de trabalho na indústria da construção.',
        price: '49,90',
        horary: '4 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 18 – Condição e Meio Ambiente na Construção Civil - BÁSICO 16H',
        subtitle: 'Inicial e Reciclagem',
        description: 'Esta norma regulamentadora é destinada a trabalhadores da construção civil e aborda os riscos e medidas necessárias nas condições e no meio ambiente de trabalho na indústria da construção.',
        price: '49,90',
        horary: '16 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 18 – Condição e Meio Ambiente na Construção Civil - RECICLAGEM 16H',
        subtitle: 'Inicial e Reciclagem',
        description: 'Esta norma regulamentadora é destinada a trabalhadores da construção civil e aborda os riscos e medidas necessárias nas condições e no meio ambiente de trabalho na indústria da construção.',
        price: '64,90',
        horary: '16 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - INICIAÇÃO',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '89,90',
        horary: '3 horas',
        avaliable: '12 meses',
        link: '',
    },
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - RECICLAGEM',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '89,90',
        horary: '3 horas',
        avaliable: '12 meses',
        link: '',
    },  
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - BÁSICO CLASSE 1',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '199,90',
        horary: '4 horas',
        avaliable: '12 meses',
        link: '',
    },  
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - BÁSICO CLASSE 2',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '199,90',
        horary: '6 horas',
        avaliable: '12 meses',
        link: '',
    },  
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - BÁSICO CLASSE 3',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '199,90',
        horary: '8 horas',
        avaliable: '12 meses',
        link: '',
    },  
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - INTERMEDIÁRIO CLASSE 1',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '209,90',
        horary: '12 horas',
        avaliable: '12 meses',
        link: '',
    },  
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - INTERMEDIÁRIO CLASSE 2',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '209,90',
        horary: '14 horas',
        avaliable: '12 meses',
        link: '',
    },  
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - INTERMEDIÁRIO CLASSE 3',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '209,90',
        horary: '16 horas',
        avaliable: '12 meses',
        link: '',
    },  
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - ESPECÍFICO CLASSE 1',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '209,90',
        horary: '14 horas',
        avaliable: '12 meses',
        link: '',
    }, 
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - ESPECÍFICO CLASSE 2',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '209,90',
        horary: '14 horas',
        avaliable: '12 meses',
        link: '',
    }, 
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - ESPECÍFICO CLASSE 3',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '209,90',
        horary: '16 horas',
        avaliable: '12 meses',
        link: '',
    }, 
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - AVANÇADO CLASSE 1',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '229,90',
        horary: '20 horas',
        avaliable: '12 meses',
        link: '',
    }, 
    {
        title: 'NR 20 – Inflamáveis e Combustíveis - AVANÇADO CLASSE 2',
        subtitle: 'Classe I,II e III – Iniciação, Básico, intermediário e avançado',
        description: 'Esta norma regulamentadora tem como objetivo capacitar profissional com requisitos mínimos para a gestão de segurança do trabalho contra fatores de risco de acidentes provenientes das atividades de produtos inflamáveis. Deixando apto para o trabalho e regulamentado conforme as exigências do ministério do trabalho.',
        price: '229,90',
        horary: '32 horas',
        avaliable: '12 meses',
        link: '',
    }, 
    {
        title: 'NR 23 – Proteção e Combate a Incêndio - COMBATE E PROTEÇÃO CONTRA INCENDIO',
        subtitle: 'Proteção contra incêndios no ambiente de trabalho',
        description: 'Esta norma regulamentadora é destinado a profissionais para conhecer os conceitos e aprimorar seus conhecimentos sobre a área de combate dos princípios de incêndios.',
        price: '145,90',
        horary: '16 horas',
        avaliable: '12 meses',
        link: '',
    },  
    {
        title: 'Primeiros Socorros',
        subtitle: 'Bombeiros, brigadistas, etc',
        description: 'O Treinamento de Primeiros Socorros aborda todo conteúdo sobre as técnicas de primeiros socorros e o conjunto de medidas de prevenção, para ser aplicado em casos de necessidade.',
        price: '150,00',
        horary: '10 horas',
        avaliable: '12 meses',
        link: '',
    },  
    {
        title: 'Direção Defensiva',
        subtitle: 'Veículos Leves e Pesados',
        description: 'O Curso de Direção Defensiva aborda todo conteúdo sobre as técnicas de direção defensiva e o conjunto de medidas de prevenção de acidentes no trânsito.',
        price: '59,90',
        horary: '6 horas',
        avaliable: '12 meses',
        link: '',
    },  
    {
        title: 'Nr 33 – Segurança e Saúde em Espaços Confinados - SUPERVISOR DE ENTRADA – BÁSICO',
        subtitle: 'Trabalhador autorizado, Vigia e Supervisor – Básico e reciclagem',
        description: 'Esta norma tem como objetivo estabelecer os requisitos mínimos para identificação de espaços confinados e o reconhecimento, avaliação, monitoramento e controle dos riscos existentes, de forma a garantir permanentemente a segurança dos trabalhadores que interagem direta ou indiretamente nestes espaços.',
        price: '169,90',
        horary: '20 horas',
        avaliable: '12 meses',
        link: '',
    },  
    {
        title: 'Nr 33 – Segurança e Saúde em Espaços Confinados - SUPERVISOR DE ENTRADA – RECICLAGEM',
        subtitle: 'Trabalhador autorizado, Vigia e Supervisor – Básico e reciclagem',
        description: 'Esta norma tem como objetivo estabelecer os requisitos mínimos para identificação de espaços confinados e o reconhecimento, avaliação, monitoramento e controle dos riscos existentes, de forma a garantir permanentemente a segurança dos trabalhadores que interagem direta ou indiretamente nestes espaços.',
        price: '99,90',
        horary: '4 horas',
        avaliable: '12 meses',
        link: '',
    },  
    {
        title: 'Nr 33 – Segurança e Saúde em Espaços Confinados - TRABALHADOR AUTORIZADO E VIGIA – BÁSICO',
        subtitle: 'Trabalhador autorizado, Vigia e Supervisor – Básico e reciclagem',
        description: 'Esta norma tem como objetivo estabelecer os requisitos mínimos para identificação de espaços confinados e o reconhecimento, avaliação, monitoramento e controle dos riscos existentes, de forma a garantir permanentemente a segurança dos trabalhadores que interagem direta ou indiretamente nestes espaços.',
        price: '129,90',
        horary: '8 horas',
        avaliable: '12 meses',
        link: '',
    }, 
    {
        title: 'Nr 33 – Segurança e Saúde em Espaços Confinados - TRABALHADOR AUTORIZADO E VIGIA – RECICLAGEM',
        subtitle: 'Trabalhador autorizado, Vigia e Supervisor – Básico e reciclagem',
        description: 'Esta norma tem como objetivo estabelecer os requisitos mínimos para identificação de espaços confinados e o reconhecimento, avaliação, monitoramento e controle dos riscos existentes, de forma a garantir permanentemente a segurança dos trabalhadores que interagem direta ou indiretamente nestes espaços.',
        price: '99,90',
        horary: '4 horas',
        avaliable: '12 meses',
        link: '',
    }, 
    {
        title: 'Nr 35 – Trabalho em Altura - BÁSICO',
        subtitle: 'Básico e Reciclagem ',
        description: 'Esta norma regulamentadora tem como objetivo capacitar o profissional para realizar trabalho em altura. Dentre elas envolve o planejamento, organização e execução da função, visa a segurança e a saúde dos trabalhadores envolvidos com atividades de risco de quedas. Deixando apto para o trabalho e regulamentado conforme as exigências no ministério do trabalho.',
        price: '129,90',
        horary: '8 horas',
        avaliable: '12 meses',
        link: '',
    }, 
    {
        title: 'Nr 35 – Trabalho em Altura - RECICLAGEM',
        subtitle: 'Básico e Reciclagem ',
        description: 'Esta norma regulamentadora tem como objetivo capacitar o profissional para realizar trabalho em altura. Dentre elas envolve o planejamento, organização e execução da função, visa a segurança e a saúde dos trabalhadores envolvidos com atividades de risco de quedas. Deixando apto para o trabalho e regulamentado conforme as exigências no ministério do trabalho.',
        price: '99,90',
        horary: '8 horas',
        avaliable: '12 meses',
        link: '',
    }, 
]